### ISSUE TITLE
Critical BCODB API endpoints

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#166]
Identify which of these 32 API endpoints are critical or high-priority for the project's requirements.

# Used by [USERDB](https://github.com/biocompute-objects/portal_userdb/tree/main/server)
- [x] #168
- [x] #169
- [x] #170
- [x] #171
- [x] #172

# Used by [BCO Portal](https://github.com/biocompute-objects/portal_userdb/tree/main/client)
- [x] #173
- [x] #174
- [x] #175
- [x] #168
- [x] #176
- [x] #177
- [x] #178
- [x] #179
- [x] #180
- [x] #181
- [x] #182
- [x] #183

**Comment by HadleyKing** [comment]
- [ ] thing

**Comment by Reeya123** [comment]
# Additional endpoints mentioned in BCO API docs. 
## Account Management:

- [ ] [Develop tests and document '/api​/accounts​/activate​/{username}​/{temp_identifier}'](https://github.com/biocompute-objects/bco_api/issues/226)
- [ ] [Develop tests and document '/api/accounts/new/'](https://github.com/biocompute-objects/bco_api/issues/230)
- [ ] [Develop tests and document '/api/objects/' ](https://github.com/biocompute-objects/bco_api/issues/229)
## API

- [ ] [Develop tests and document '/api​/verify​/' ](https://github.com/biocompute-objects/bco_api/issues/228)
- [ ] [Develop tests and document '/api/token/'](https://github.com/biocompute-objects/bco_api/issues/227)

## Group Management:

- [ ] [Develop tests and document '/api/groups/create/'](https://github.com/biocompute-objects/bco_api/issues/235)
- [ ] [Develop tests and document '/api/groups/delete/'](https://github.com/biocompute-objects/bco_api/issues/234)

## BCO Management:

- [ ] [Develop tests and document '/api​/objects​/drafts​/permissions​/'](https://github.com/biocompute-objects/bco_api/issues/233)

- [ ] [Develop tests and document '/api/objects/drafts/permissions/set/'](https://github.com/biocompute-objects/bco_api/issues/232)
- [ ] [Develop tests and document '/api​/objects​/drafts​/read​/'](https://github.com/biocompute-objects/bco_api/issues/231)
- [ ] [Develop tests and document '/api/objects/drafts/token/'](https://github.com/biocompute-objects/bco_api/issues/240)
- [ ] [Develop tests and document '/api/objects/publish/'](https://github.com/biocompute-objects/bco_api/issues/239)
- [ ] [Develop tests and document '/api​/objects​/published​/'](https://github.com/biocompute-objects/bco_api/issues/238)
- [ ] [Develop tests and document '/api/objects/token/'](https://github.com/biocompute-objects/bco_api/issues/237)
- [ ] [Develop tests and document '/{object_id}​/DRAFT](https://github.com/biocompute-objects/bco_api/issues/236)
- [ ] [Develop tests and document '/{object_id_root}​/{object_id_version}'](https://github.com/biocompute-objects/bco_api/issues/245)

## Prefix Management:

- [ ] [Develop tests and document '/api/prefixes/delete/'](https://github.com/biocompute-objects/bco_api/issues/244)
- [ ] [Develop tests and document '/api/prefixes/permissions/set/'](https://github.com/biocompute-objects/bco_api/issues/243)
- [ ] [Develop tests and document '/api/prefixes/token/flat/' ](https://github.com/biocompute-objects/bco_api/issues/242)

## API Information:

- [ ] [Develop tests and document '/api/public/describe/'](https://github.com/biocompute-objects/bco_api/issues/241)
