### ISSUE TITLE
Prefix Management

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/bco_api#63]
Test and add OpenAPI docs to the `views.py` file for each of the Prefix Management API endpoints:
- [ ] `api/prefixes/create` Issue biocompute-objects/bco_api#61 
- [ ] `api/prefixes/delete` Issue biocompute-objects/portal#103 
- [ ] `api/prefixes/permissions/set` Issue biocompute-objects/portal#104
- [ ] `api/prefixes/token` Issue biocompute-objects/portal#105
- [ ] `api/prefixes/update` Issue biocompute-objects/bco_api#62

**Comment by HadleyKing** [comment]
Repurposed as a PR
